import {formatSlideText} from './slide-tools.js?v=20260930l';
import {loginPanel} from './email-login.js?v=20260930l';
import {renderLegal} from './legal.js?v=20260930l';
import {renderPractice} from './practice.js?v=20260930l';
import {accountTools} from './account-tools.js?v=20260930l';
import {renderLibrary,courseMaterials} from './library.js?v=20260930l';
import {config} from './config.js?v=20260930l';
import {hasAccess,shuffle,safeURL,scopeLabel} from './policy.mjs?v=20260930l';
const main=document.querySelector('main');
const returningFromLogin=new URLSearchParams(location.search).has('code')||new URLSearchParams(location.hash.slice(1)).has('error');
let loginReturnFailed=false;
let catalog,user=null,grants=[],auth=null,routeVersion=0,expiryTimer;
function watchExpiry(){clearTimeout(expiryTimer);const next=grants.filter(g=>!g.revoked_at).map(g=>Date.parse(g.expires_at)).filter(t=>t>Date.now()).sort((a,b)=>a-b)[0];if(next)expiryTimer=setTimeout(()=>{document.querySelectorAll('.image-dialog').forEach(d=>d.remove());route();},Math.min(next-Date.now()+50,2147483647));}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&catalog)route();});
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const link=(text,href,cls)=>{const a=el('a',text,cls);a.href=href;return a;};
function external(text,url){const href=safeURL(url);if(!href)return el('span',text);const a=link(text,href);a.target='_blank';a.rel='noopener noreferrer';return a;}
function button(text,action,cls=''){const b=el('button',text,cls);b.type='button';b.addEventListener('click',action);return b;}
function card(title){const n=el('section',undefined,'card');if(title)n.append(el('h2',title));return n;}
function list(items){const ul=el('ul');for(const x of items??[])ul.append(el('li',x));return ul;}
function status(text){const n=el('p',text,'status');n.role='status';return n;}
function allowed(c){return c.free||hasAccess(`course:${String(c.no).padStart(2,'0')}`,grants);}
function badge(c){return el('span',c.free?'Kostenlos':allowed(c)?'✓ Freigeschaltet':'🔒 Mit Code freischalten',`badge ${allowed(c)?'':'lock'}`);}
function courseCard(c){const n=card();n.append(badge(c),el('p',`KURS ${String(c.no).padStart(2,'0')}`,'section-number'),el('h2',c.title),el('p',c.subtitle),link('Kurs ansehen →',`#course/${c.id}`,'button secondary'));return n;}
function home(){const hero=el('section',undefined,'hero'),copy=el('div',undefined,'hero-copy');copy.append(el('p','Medizinrecht verstehen. Sicherer handeln.','eyebrow'));const h=el('h1','Recht haben.');h.append(el('br'),el('span','Recht bekommen.'));copy.append(h,el('p','15 fallbasierte Kurse, Urteile und Normen. Für Medizin, Recht und alle Gesundheitsberufe.'),link('Kostenlos mit Kurs 1 starten →','#course/tag-01','button'));const image=el('img');image.src='assets/login-klinik-gericht-v1.webp';image.alt='Ärztin zwischen Behandlungszimmer und Gerichtssaal';hero.append(copy,image);main.append(hero,el('p','⚠ Lehr- und Lernangebot. Keine individuelle Rechts- oder medizinische Beratung.','notice disclaimer'));const intro=card('Ihr Einstieg ist kostenlos');intro.append(el('p','Kurse 1 und 2, Urteile und Normen sind ohne Anmeldung zugänglich. Weitere Kurse öffnen Sie nach der Anmeldung mit einem gültigen Freischaltcode.'),link('Alle 15 Kurse entdecken →','#courses','button secondary'));main.append(intro);}
function courses(){main.append(el('h1','Alle 15 Kurse'),el('p','Kurse 1–2 kostenlos · weitere Kurse mit Freischaltcode'));const search=el('input');search.type='search';search.placeholder='Kursnummer, Thema oder Lernziel suchen';search.setAttribute('aria-label','Kurse durchsuchen');const grid=el('div',undefined,'grid');const render=()=>{const q=search.value.toLocaleLowerCase('de');grid.replaceChildren(...catalog.catalog.filter(c=>`${c.no} ${c.title} ${c.subtitle} ${c.goals.join(' ')}`.toLocaleLowerCase('de').includes(q)).map(courseCard));};search.addEventListener('input',render);main.append(search,grid);render();}
function question(title,q){if(!q)return;const section=card(title);section.append(el('p',q.question??q.prompt??''));const answers=el('div'),feedback=status('');const options=shuffle((q.choices??[]).map((c,i)=>({i,label:typeof c==='string'?c:c.label,feedback:c.feedback})));const render=()=>{feedback.textContent='';answers.replaceChildren();for(const o of options){const b=button(o.label,()=>{const hasCorrect=Number.isInteger(q.correct),right=o.i===q.correct;for(const node of answers.children)node.disabled=true;b.classList.add(hasCorrect&&!right?'wrong':'correct');if(hasCorrect){const correct=options.find(x=>x.i===q.correct);const correctButton=[...answers.children].find(n=>n.dataset.index===String(q.correct));correctButton?.classList.add('correct');feedback.textContent=`${right?'Richtig.':'Noch nicht richtig.'} Richtige Antwort: ${correct?.label??''} ${o.feedback??q.feedback??''}`;}else feedback.textContent=o.feedback??q.feedback??'Diese Frage dient der eigenen Abwägung.';},'answer');b.dataset.index=o.i;answers.append(b);}};render();section.append(answers,feedback,button('Frage erneut beantworten',render,'secondary'));main.append(section);}
async function course(id,version){const preview=catalog.catalog.find(c=>c.id===id);main.append(link('← Kursübersicht','#courses','back'));if(!preview){main.append(el('h1','Kurs nicht gefunden'));return;}const head=card();head.classList.add('course-hero');head.append(badge(preview),el('p',`KURS ${String(preview.no).padStart(2,'0')}`,'section-number'),el('h1',preview.title),el('p',preview.subtitle),el('h2','Das lernen Sie'),list(preview.goals));main.append(head);let content=catalog.courses.find(c=>c.id===id);if(!content&&allowed(preview)&&auth&&config.backendReady){const loading=status('Kurszugang wird geprüft …');main.append(loading);try{content=await auth.getCourse(id);}catch{loading.textContent='Der Kurs konnte nicht geladen werden. Bitte versuchen Sie es erneut.';return;}if(version!==routeVersion)return;loading.remove();}if(!content){const gate=card('Diesen Kurs freischalten');gate.append(el('p','🔒 Die Vorschau ist frei zugänglich. Für die Kursinhalte melden Sie sich an und lösen Ihren Freischaltcode ein.','notice'),link(user?'Freischaltcode eingeben →':'Anmelden und Code eingeben →','#account','button'));main.append(gate);return;}for(const [i,b] of content.basics.entries()){const box=card();box.classList.add('course-foundation');box.append(el('p',`GRUNDLAGEN · ${i+1}`,'section-number'),el('h2',b.title));formatSlideText(box,b.body);if(b.norms?.length)box.append(el('p',b.norms.join(' · '),'subtle'));main.append(box);}if(content.decision){const d=content.decision,box=card('⚖ '+d.title);box.append(el('p',`${d.court} · ${d.date} · ${d.docket}`,'subtle'),el('h3','Sachverhalt'),el('p',d.facts),el('h3','Entscheidung'),el('p',d.headnote),el('p','💡 '+d.practice,'notice'),external('Entscheidung an der Quelle öffnen ↗',d.url));main.append(box);}question(content.caseTask?.title??'Ihr Fall',content.caseTask);question('Wissen prüfen',content.quiz);question('Praxistransfer',content.transfer);if(content.podcast){const box=card('🎧 Zum Podcast');box.append(el('p',content.podcast.bridge),external(content.podcast.title+' ↗',content.podcast.link));main.append(box);}const sources=card('Quellen & Vertiefung');for(const r of content.reading??[]){const p=el('p');p.append(external(r.label+' ↗',r.url));sources.append(p);}main.append(sources);await courseMaterials(main,preview.no,()=>version===routeVersion);}
function references(type){main.append(el('h1',type==='cases'?'Urteile & Einordnung':'Normen nachschlagen'));const search=el('input');search.type='search';search.setAttribute('aria-label','Quellen durchsuchen');search.placeholder='Begriff, Aktenzeichen oder Norm suchen';const results=el('div');const render=()=>{results.replaceChildren();const data=type==='cases'?catalog.landmarkCases:[...catalog.importantNorms,...(catalog.practicalResources??[])];for(const r of data.filter(r=>JSON.stringify(r).toLowerCase().includes(search.value.toLowerCase()))){const box=card(r.title??r.label);box.append(el('p',r.area??r.category,'subtle'),el('p',r.holding??r.description));if(r.practice)box.append(el('p','💡 '+r.practice,'notice'));box.append(external('Originalquelle öffnen ↗',r.url));results.append(box);}};search.addEventListener('input',render);main.append(search,results);render();}
async function account(){main.classList.add('narrow');main.append(el('h1','Mein Zugang'),el('p','Anmelden, Freischaltcode einlösen und die Laufzeit Ihres Web-Zugangs sehen.'));const msg=status('');if(!user){if(loginReturnFailed)main.append(status('Die Anmeldung wurde in diesem Browser nicht abgeschlossen. Fordern Sie unten eine neue Anmeldemail an und geben Sie deren Anmeldecode direkt hier ein. Ihr bestehendes Konto bleibt erhalten.'));main.append(loginPanel(auth,config));}else{const box=card('Angemeldet');box.append(el('p',user.email??'Ihr Konto'),button('Abmelden',async()=>{await auth.client.auth.signOut();user=null;grants=[];location.hash='#account';route();},'secondary'));main.append(box);const grantBox=card('Ihre Freischaltungen');for(const g of grants.filter(g=>hasAccess(g.scope,[g]))){grantBox.append(el('p',`${scopeLabel(g.scope)} · bis ${new Date(g.expires_at).toLocaleString('de-DE')}`));}if(!grantBox.querySelector('p'))grantBox.append(el('p','Noch kein zusätzlicher Web-Zugang aktiv. Kurse 1 und 2 bleiben kostenlos.'));main.append(grantBox);const form=el('form',undefined,'card'),label=el('label','Freischaltcode'),input=el('input');input.id='code';input.required=true;input.maxLength=128;input.autocomplete='off';label.htmlFor=input.id;const submit=el('button','Code einlösen');submit.type='submit';submit.disabled=!config.backendReady;form.append(label,input,submit);form.addEventListener('submit',async e=>{e.preventDefault();submit.disabled=true;try{const r=await auth.redeem(input.value.trim());if(r.ok){grants=await auth.getGrants();await route();const done=status(r.already_redeemed?'Dieser Code wurde bereits für Ihr Konto eingelöst. Die aktuelle Laufzeit steht bei Ihren Freischaltungen.':'Ihr Webzugang ist freigeschaltet. Die Laufzeit steht bei Ihren Freischaltungen.');main.prepend(done);return;}msg.textContent=r.reason==='try_later'?'Zu viele Versuche. Bitte warten Sie 15 Minuten.':'Der Code ist nicht verfügbar, abgelaufen oder bereits vollständig eingelöst.';}catch{msg.textContent='Die Freischaltung konnte nicht geprüft werden. Bitte versuchen Sie es erneut.';}finally{submit.disabled=false;}});main.append(form,accountTools(auth,()=>{user=null;grants=[];route().then(()=>main.prepend(status('Ihr Web-Konto wurde gelöscht.')));}));}main.append(msg,el('p','Web-Codes gelten für diese Lernplattform. Apple-Abos und App-Store-Angebotscodes werden hier nicht automatisch übernommen.','notice'));}
async function route(){document.querySelectorAll('.image-dialog').forEach(d=>d.remove());watchExpiry();const version=++routeVersion;main.classList.remove('narrow','presentation-player');main.replaceChildren();const [page,id]=location.hash.slice(1).split('/');if(page==='library'||page==='material'||page==='slides')await renderLibrary(main,page==='material'&&id?decodeURIComponent(id):null,auth,grants,()=>version===routeVersion,page==='slides'?'slides':page==='library'?id:null);else if(page==='practice')await renderPractice(main,auth,grants,user,()=>version===routeVersion);else if(page==='courses')courses();else if(page==='course')await course(id,version);else if(['cases','norms'].includes(page))references(page);else if(page==='account')await account();else if(['privacy','terms'].includes(page))renderLegal(main,page);else home();}
try{catalog=await fetch('./catalog.json').then(r=>{if(!r.ok)throw Error();return r.json();});await route();window.addEventListener('hashchange',()=>{window.scrollTo(0,0);route();});try{auth=await import('./auth.js?v=20260930l');user=await auth.currentUser();loginReturnFailed=returningFromLogin&&!user;if(returningFromLogin)location.hash='#account';if(user)grants=await auth.getGrants();auth.client.auth.onAuthStateChange(()=>setTimeout(async()=>{try{user=await auth.currentUser();if(user)loginReturnFailed=false;grants=user?await auth.getGrants():[];await route();}catch{grants=[];main.prepend(status('Der Zugang konnte gerade nicht geprüft werden. Bitte laden Sie die Seite erneut.'));}},0));await route();}catch{if(location.hash==='#account')await route();}}catch{main.replaceChildren(el('h1','Lernplattform nicht erreichbar'),el('p','Bitte laden Sie die Seite erneut.'));}

window.addEventListener('keydown',event=>{if(!main.classList.contains('presentation-player')||/INPUT|SELECT|TEXTAREA/.test(event.target.tagName)||event.ctrlKey||event.metaKey||event.altKey)return;const links=main.querySelectorAll('.player-controls a');const target=event.key==='ArrowRight'?[...links].find(a=>a.textContent.includes('Nächste')):event.key==='ArrowLeft'?[...links].find(a=>a.textContent.includes('Vorherige')):null;if(target){event.preventDefault();target.click();}else if(event.key==='Escape')location.hash='#slides';});
