const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
const link=(text,href)=>{const a=el('a',text,'button secondary');a.href=href;return a;};
export function renderLearningOffer(main,catalog){
  main.append(link('← Zur Startseite','#home'));
  const hero=el('section',null,'knowledge-banner');hero.append(el('p','ORIENTIERUNG · KURSZIELE · PODCAST','section-number'),el('h1','✨ Lernangebot entdecken'),el('p','Medizinrecht verstehen. Sicher handeln. Auf Verfahren vorbereitet sein.'));main.append(hero);
  const path=el('section',null,'card');path.append(el('h2','🧭 Ihr medizinrechtlicher Lernpfad'));
  const image=el('img');image.src='assets/learning-path.png';image.alt='Lernpfad von der Behandlung über Dokumentation und Begutachtung bis zur Verhandlung';image.className='learning-path-image';path.append(image,el('p','Von der Behandlung bis zur Verhandlung: Die 15 Kurse verbinden Grundlagen, Fälle, Leitentscheidungen, Wissensfragen und Praxistransfer.'),link('Alle Kurse entdecken →','#courses'));main.append(path);
  const goals=el('section',null,'card');goals.append(el('h2','🎯 Was Sie am Ende können'));const list=el('ol',null,'learning-outcomes');for(const outcome of catalog.outcomes??[])list.append(el('li',outcome));goals.append(list);main.append(goals);
  const progress=el('section',null,'card');progress.append(el('h2','📈 Ihr Fortschritt wird sichtbar'),el('p','Jeder bearbeitete Lernschritt zählt. Sehen Sie Ihren Stand je Kurs, den Gesamtfortschritt und Ihre Erfahrungspunkte. Nach Abschluss aller 15 Kurse können Sie Ihr persönliches Lernzertifikat erstellen.'),el('p','Als Gast bleibt der Lernstand in diesem Browser. Mit einem Web-Konto können Sie ihn zwischen Ihren Browsern und Geräten synchronisieren. App und Website verwalten Lernstand und Zugänge getrennt.','subtle'),link('Meinen Fortschritt ansehen →','#progress'));main.append(progress);
  const podcast=el('section',null,'card');podcast.append(el('h2','🎧 Lernen und weiterhören'),el('p','Recht Medizinisch mit Florian Schlepple und Dr. Philipp Graef: Podcast-Fälle treffen auf Normen, Leitentscheidungen, Erklärungen und passende Schaubilder.'),link('Podcast & Materialien →','#podcast'),link('Philipp Graef · Homepage ↗','https://philippgraef.github.io/'));main.append(podcast);
  main.append(el('p','⚠ Lehr- und Lernangebot. Keine individuelle Rechts- oder medizinische Beratung. Das Lernzertifikat ist ein Nachweis innerhalb der Plattform, keine berufsrechtliche Qualifikation oder CME-Anerkennung.','notice disclaimer'));
}
