const node=(tag,text)=>{const n=document.createElement(tag);n.textContent=text;return n;};
export function renderLegal(main,type){
 main.classList.add('narrow');
 const link=(title,url)=>{const a=node('a',title+' ↗');a.href=url;a.rel='noopener noreferrer';return a;};
 main.append(node('h1',type==='terms'?'Nutzung der Lernplattform':'Datenschutzerklärung'),node('p','Stand: 30. September 2026 · Web-Lernplattform Recht Medizinisch'));
 if(type==='terms'){
  for(const [title,text] of [
   ['Lernen und Nachschlagen','Recht Medizinisch ist ein Lehr- und Lernangebot für Medizinrecht. Die Inhalte ersetzen keine Rechtsberatung, medizinische Beratung, individuelle Diagnostik oder Therapie. Sie sind kein Instrument zur Entscheidung über die Behandlung einzelner Patienten. Maßgeblich bleiben die im Einzelfall anwendbaren Regeln und aktuellen Originalquellen.'],
   ['Kostenloser Einstieg und Freischaltungen','Kurse 1 und 2 sowie die als kostenlos gekennzeichneten Materialien können frei genutzt werden. Weitere Inhalte benötigen einen passenden Web-Freischaltcode. Bei jedem Code gelten der ausdrücklich genannte Umfang, die Einlösefrist und die Zugangsdauer. Ihre aktive Freischaltung und ihr Ablauf erscheinen unter „Mein Zugang“. Ein Code kann pro Konto nur einmal eingelöst werden.'],
   ['Unabhängig von der iPhone-App','Diese Website hat eigene Zugangsberechtigungen. Apple-Abonnements und App-Store-Angebotscodes werden nicht automatisch in einen Web-Zugang umgewandelt. Hier werden derzeit keine Abonnements oder Einzelkäufe abgeschlossen. Die Eingabe eines Freischaltcodes löst keine automatische Zahlung oder Vertragsverlängerung aus.'],
   ['Persönliche Nutzung','Nutzen Sie die bereitgestellten Texte, Fragen und Schaubilder für Ihr persönliches Lernen. Eine Veröffentlichung, Weiterverteilung oder kommerzielle Übernahme geschützter Inhalte benötigt die Zustimmung des jeweiligen Rechteinhabers, soweit nicht eine gesetzliche Erlaubnis greift. Kennzeichnungen, Quellenangaben und Rechte Dritter bleiben bestehen.'],
   ['Konto und Sicherheit','Bewahren Sie Anmeldelinks und persönliche Freischaltcodes vertraulich auf. Melden Sie sich auf gemeinsam genutzten Geräten ab. Bei Kontolöschung werden Web-Freischaltungen entfernt; verbrauchte Codes werden dadurch nicht wieder frei. Apple-Abos werden durch eine Web-Kontolöschung nicht gekündigt.'],
   ['Fragen und Korrekturen','Hinweise auf Fehler, fehlende Aktualisierungen oder Zugangsprobleme nehmen wir unter rechtmedizinisch@gmail.com entgegen. Bitte übermitteln Sie keine identifizierbaren Patienten- oder Falldaten.']
  ]) main.append(node('h2',title),node('p',text));
  return;
 }
 for(const [title,text] of [
  ['Verantwortlicher','Philipp Graef, Holzbronner Str. 55, 75365 Calw, Deutschland. Datenschutzkontakt: rechtmedizinisch@gmail.com.'],
  ['Website-Aufruf','Die Website wird über GitHub Pages bereitgestellt. Beim Abruf werden technisch notwendige Verbindungsdaten wie IP-Adresse, Browserinformationen, aufgerufene Ressource und Zeitpunkt vom Hostingdienst verarbeitet. Zweck sind Auslieferung und sicherer Betrieb. Rechtsgrundlage für unser berechtigtes Interesse daran ist Art. 6 Abs. 1 lit. f DSGVO. Wir binden keine Werbe- oder Analysewerkzeuge ein.'],
  ['Anmeldung und Freischaltcodes','Kostenlose Inhalte können ohne Konto gelesen werden. Für geschützte Inhalte verarbeiten wir Ihre E-Mail-Adresse, eine interne Konto-ID, Anmeldeinformationen, die Zuordnung eingelöster Codes sowie Umfang, Beginn und Ablauf Ihrer Freischaltungen. Supabase stellt Anmeldung, Datenbank und geschützten Dateispeicher bereit; das Projekt liegt in der Region Frankfurt. Die Daten werden zur Bereitstellung des gewünschten Kontos und Zugangs gemäß Art. 6 Abs. 1 lit. b DSGVO verarbeitet. Sicherheitsprotokolle und die Begrenzung von Codeversuchen dienen der Missbrauchsabwehr auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO.'],
  ['Mit Google anmelden','Wenn Sie diese Alternative wählen, übermittelt Google nach Ihrer Bestätigung die für die Anmeldung erforderliche Konto-ID, E-Mail-Adresse sowie grundlegende Profilinformationen wie Name und gegebenenfalls Profilbild an Supabase. Die Anmeldung erlaubt keinen Zugriff auf Ihre Gmail-Nachrichten oder Google-Drive-Dateien. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO für die von Ihnen gewählte Kontofunktion. Sie können stattdessen die E-Mail-Anmeldung verwenden.'],
  ['E-Mail-Versand und Kontakt','Anmelde- und Bestätigungsmails werden über das Google-/Gmail-Postfach rechtmedizinisch@gmail.com versendet. Dabei werden Empfängeradresse, Nachrichteninhalt und technische Versanddaten durch Google verarbeitet. Die E-Mail enthält einen persönlichen, zeitlich begrenzten Anmeldelink. Geben Sie diesen nicht weiter. Es wird dadurch kein Newsletter abonniert. Supportnachrichten werden zur Bearbeitung Ihrer Anfrage verarbeitet; Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO bei vertragsbezogenen Anliegen, sonst Art. 6 Abs. 1 lit. f DSGVO. Das Logo in E-Mails wird von GitHub Pages geladen, wenn Ihr Mailprogramm externe Bilder abruft. Wir verwenden dafür keine individuellen Öffnungs- oder Trackingkennungen.'],
  ['Browserspeicher und Übungsdaten','Die Anmeldung speichert Sitzungstoken im lokalen Browserspeicher, damit Sie angemeldet bleiben. Das Fehlertraining speichert Fragenkennungen getrennt nach Web-Konto nur in diesem Browser. Es wird nicht an Supabase oder iCloud übertragen. Diese Speicherung dient den von Ihnen aufgerufenen Funktionen (§ 25 Abs. 2 Nr. 2 TDDDG); die Verarbeitung des Lernstands erfolgt zur gewünschten Lernfunktion gemäß Art. 6 Abs. 1 lit. b DSGVO. Abmelden beendet die Sitzung, entfernt aber die lokale Fehlerliste nicht. Über die Website-Daten-Einstellungen Ihres Browsers können Sie lokale Daten löschen.'],
  ['Speicherdauer und Löschung','Kontodaten und die Zuordnung Ihrer Freischaltungen bleiben für die Kontoführung gespeichert, bis Sie das Web-Konto unter „Mein Zugang“ löschen oder die Löschung bei uns anfordern. Mit der Löschung werden die zugeordneten Freischaltungen, Codeeinlösungen und Versuchszähler entfernt. Ein bereits verbrauchter Code wird nicht wieder frei. Technische Protokolle und Sicherungen unterliegen den Löschzyklen der eingesetzten Dienste. Erledigte Supportkorrespondenz wird gelöscht, sobald sie nicht mehr benötigt wird und keine gesetzlichen Aufbewahrungs- oder Rechtsverteidigungsgründe entgegenstehen.'],
  ['Empfänger und internationale Verarbeitung','Neben uns erhalten die genannten Hosting-, Authentifizierungs- und E-Mail-Dienste die für ihre jeweilige Aufgabe notwendigen Daten. Eine Verarbeitung außerhalb des EWR kann insbesondere durch internationale Anbieter und deren Unterauftragnehmer stattfinden. Informationen zu deren Standorten, Übermittlungsgarantien und Unterauftragnehmern finden Sie in den nachstehenden Anbieterinformationen. Die gewählte Datenbankregion bedeutet nicht, dass sämtliche Dienstverarbeitung ausschließlich in Deutschland erfolgt.'],
  ['App, Apple und externe Inhalte','Die Website liest weder Ihren Apple-Account noch Ihren privaten iCloud-Lernstand aus. Apple-Käufe werden nicht automatisch übernommen. Quellen- und Podcastlinks werden erst bei Ihrer Auswahl geöffnet; anschließend gelten die Datenschutzhinweise des jeweiligen Anbieters.'],
  ['Ihre Rechte','Unter den gesetzlichen Voraussetzungen haben Sie Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch gegen eine Verarbeitung auf Grundlage berechtigter Interessen. Einwilligungen können Sie, soweit eine Verarbeitung darauf beruht, für die Zukunft widerrufen. Wenden Sie sich an rechtmedizinisch@gmail.com. Sie können sich bei einer Datenschutzaufsichtsbehörde beschweren, insbesondere beim Landesbeauftragten für den Datenschutz und die Informationsfreiheit Baden-Württemberg. Es erfolgt keine automatisierte Entscheidung mit rechtlicher oder vergleichbar erheblicher Wirkung. Ohne E-Mail-Adresse ist die Kontofunktion nicht nutzbar; die kostenlosen Inhalte bleiben zugänglich.']
 ])main.append(node('h2',title),node('p',text));
 const ul=document.createElement('ul');for(const [title,url] of [
  ['GitHub-Datenschutz','https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement'],
  ['Supabase: Vereinbarung zur Datenverarbeitung','https://supabase.com/legal/customer-resources/data-processing-addendum'],
  ['Google-Datenschutz','https://policies.google.com/privacy?hl=de'],
  ['Datenschutzaufsicht Baden-Württemberg','https://www.baden-wuerttemberg.datenschutz.de/beschwerde/']
 ]){const li=document.createElement('li');li.append(link(title,url));ul.append(li);}main.append(ul);
}
