import {safeURL} from './policy.mjs?v=20260930al';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
const link=(text,href,cls)=>{const a=el('a',text,cls);a.href=href;if(href.startsWith('https:')){a.target='_blank';a.rel='noopener noreferrer';}return a;};
export async function renderPodcast(main,isCurrent,selectedId){
  const hero=el('section',null,'podcast-hero'),image=el('img');image.src='assets/podcast-cover.webp';image.alt='Recht Medizinisch – Podcast';
  const copy=el('div');copy.append(el('p','HÖREN · VERSTEHEN · VERTIEFEN','section-number'),el('h1','🎧 Recht Medizinisch'),el('p','Mit Florian Schlepple & Dr. Philipp Graef','podcast-hosts'),el('p','Medizin, Pflege und Recht im Gespräch. Finden Sie zur Folge die passenden Kurse und Schaubilder.'),link('Alle Folgen bei Spotify ↗','https://open.spotify.com/show/7aowMbc68QlEwd0K4x5OT8','button secondary'));
  hero.append(image,copy);main.append(hero);
  const response=await fetch('./podcast-episodes.json?v=20260930al');if(!response.ok)throw Error('Podcastfolgen konnten nicht geladen werden.');const episodes=await response.json();
  const libraryResponse=await fetch('./library.json?v=20260930al');if(!libraryResponse.ok)throw Error('Materialverweise konnten nicht geladen werden.');const library=await libraryResponse.json();if(!isCurrent())return;
  const search=el('input');search.type='search';search.placeholder='Folge oder Thema suchen';search.setAttribute('aria-label','Podcastfolgen durchsuchen');const count=el('p',null,'subtle');count.role='status';const grid=el('div',null,'podcast-grid');
  function render(){grid.replaceChildren();const q=search.value.trim().toLocaleLowerCase('de'),matches=episodes.filter(e=>`${e.label} ${e.title} ${e.summary}`.toLocaleLowerCase('de').includes(q));count.textContent=`${matches.length} ${matches.length===1?"Folge / Kurzvisite":"Folgen und Kurzvisiten"}`;for(const e of matches){const card=el('article',null,'card podcast-episode');card.append(el('p',`${e.label} · ${e.duration} Min.`,'section-number'),el('h2',e.title),el('p',e.summary));if(e.note)card.append(el('p',e.note,'subtle'));if(safeURL(e.url))card.append(link(e.id==='intro'?'Trailer in der Folgenübersicht hören ↗':'Folge hören ↗',e.url,'button'));const related=el('div',null,'podcast-related');related.append(el('h3','Passend weiterlernen'));for(const n of e.courses)related.append(link(`🎓 Kurs ${String(n).padStart(2,'0')} öffnen →`,`#course/tag-${String(n).padStart(2,'0')}`));for(const id of e.materials){const m=library.find(x=>x.id===id);if(m)related.append(link(`▧ ${m.title} →`,'#material/'+encodeURIComponent(id)));}card.append(related);grid.append(card);}if(!matches.length)grid.append(el('p','Keine passende Folge. Versuchen Sie einen anderen Begriff.','notice'));}
  if(selectedId){const selected=episodes.find(e=>e.id===selectedId);if(selected)search.value=selected.title;}main.append(search,count,grid);render();search.addEventListener('input',render);
  const about=el('section',null,'card');about.append(el('h2','Die Menschen hinter dem Podcast'),el('p','Florian Schlepple und Dr. Philipp Graef verbinden Perspektiven aus Pflege, Medizin und Recht.'),link('Philipp Graef: Profil, Publikationen und Projekte ↗','https://philippgraef.github.io/'),el('p','Podcast und Lernplattform dienen der Information und Lehre; sie ersetzen keine individuelle medizinische oder rechtliche Beratung.','notice'));main.append(about);
}
