const exact={kernpunkte:['☷','teal'],kernaussage:['❝','teal'],'tragende aussage':['❝','teal'],zitat:['❝','teal'],einordnung:['🧭','indigo'],kontext:['🧭','indigo'],ausgangspunkt:['🧭','indigo'],'historische einordnung':['🧭','indigo'],funktion:['⚙','blue'],methode:['⚙','blue'],kriterien:['⚙','blue'],kausalität:['🔗','teal'],rollen:['👥','teal'],aufklärung:['💬','blue'],einwilligung:['✓','teal'],berufsrecht:['🪪','blue'],zivilrecht:['👥','teal'],strafrecht:['⚖','indigo'],verfahren:['☷','teal'],kommunikation:['💬','blue'],akte:['📂','teal'],approbationsrecht:['🪪','blue'],rechtsfolge:['↳','teal'],anfangsverdacht:['🔎','teal'],grenzen:['⚠','gold'],sachverhalt:['🧩','blue'],fall:['🧩','blue'],beispiel:['🧩','blue'],fallbeispiel:['🧩','blue'],praxisfall:['🧩','blue'],'fiktives fallbeispiel':['🧩','blue'],'fiktiver übungsfall':['🧩','blue'],leitfrage:['?','indigo'],leitfragen:['?','indigo'],entscheidung:['⚖','indigo'],norm:['⚖','indigo'],normen:['⚖','indigo'],dokumentation:['📝','teal'],beweis:['🔎','teal'],evidenz:['🔎','teal'],befund:['🔎','teal'],praxis:['🩺','teal'],lehrtransfer:['🩺','teal'],patientensicherheit:['✚','teal'],'podcast-folge':['🎙','teal'],arbeitsauftrag:['☑','teal'],arbeitsaufträge:['☑','teal']};
const prefixes=[[/^(fundstelle|quelle)/,'📚','blue'],[/^(achtung|warnung)/,'⚠','gold'],[/^(merksatz|praxis-merksatz|merke)/,'💡','gold'],[/^hinweis/,'ℹ','teal'],[/^(definition|legaldefinition)/,'📖','teal'],[/^checkliste/,'☑','teal'],[/^(lernziel|ihre lernziele)/,'🎯','teal'],[/^(problem|rechtsfrage)/,'?','indigo']];
export function headingStyle(title=''){
 const steps=['Tod feststellen','Prognose klären','Willen ermitteln','Rollen trennen','Prozess sichern'];const step=steps.indexOf(title),numbered=title.match(/^(\d{1,2}[.)]?|[A-C][.)])\s+(.+)$/);
 if(step>=0)return {symbol:String(step+1),tone:'teal',title,step:true};if(numbered)return {symbol:numbered[1].replace(/[.)]/g,''),tone:'teal',title:numbered[2],step:true};
 const key=title.toLocaleLowerCase('de').trim(),entry=exact[key],prefix=prefixes.find(([re])=>re.test(key));return {symbol:entry?.[0]??prefix?.[1]??'',tone:entry?.[1]??prefix?.[2]??'plain',title,step:false};
}
export function protectReferences(text){return text.replace(/(§{1,2}|\bArt\.|\bAbs\.|\bSatz|\bNr\.)[ \t]+(?=\d)/g,'$1\u00a0');}
export function slideSections(blocks){const sections=[],sources=[];for(const b of blocks){if(b.role==='source'){if(b.text&&!sources.includes(b.text))sources.push(b.text);continue;}if(b.role==='heading'){const title=b.text.replace(/ · Fortsetzung$/,'');if(sections.at(-1)?.title!==title)sections.push({title,blocks:[]});}else{if(!sections.length||b.image)sections.push({title:'',blocks:[]});const section=sections.at(-1),last=section.blocks.at(-1);if(b.continuesPrevious&&last?.role==='body'&&b.role==='body')section.blocks[section.blocks.length-1]={...last,text:last.text+' '+b.text,links:[...(last.links??[]),...(b.links??[])]};else section.blocks.push(b);}}return {sections,sources};}
