const exact={kernpunkte:['☷','teal'],kernaussage:['❝','teal'],'tragende aussage':['❝','teal'],zitat:['❝','teal'],einordnung:['🧭','indigo'],kontext:['🧭','indigo'],ausgangspunkt:['🧭','indigo'],'historische einordnung':['🧭','indigo'],funktion:['⚙','blue'],methode:['⚙','blue'],kriterien:['⚙','blue'],kausalität:['🔗','teal'],rollen:['👥','teal'],aufklärung:['💬','blue'],einwilligung:['✓','teal'],berufsrecht:['🪪','blue'],zivilrecht:['👥','teal'],strafrecht:['⚖','indigo'],verfahren:['☷','teal'],kommunikation:['💬','blue'],akte:['📂','teal'],approbationsrecht:['🪪','blue'],rechtsfolge:['↳','teal'],anfangsverdacht:['🔎','teal'],grenzen:['⚠','gold'],sachverhalt:['🧩','blue'],fall:['🧩','blue'],beispiel:['🧩','blue'],fallbeispiel:['🧩','blue'],praxisfall:['🧩','blue'],'fiktives fallbeispiel':['🧩','blue'],'fiktiver übungsfall':['🧩','blue'],leitfrage:['?','indigo'],leitfragen:['?','indigo'],entscheidung:['⚖','indigo'],norm:['⚖','indigo'],normen:['⚖','indigo'],dokumentation:['📝','teal'],beweis:['🔎','teal'],evidenz:['🔎','teal'],befund:['🔎','teal'],praxis:['🩺','teal'],lehrtransfer:['🩺','teal'],patientensicherheit:['✚','teal'],'podcast-folge':['🎙','teal'],arbeitsauftrag:['☑','teal'],arbeitsaufträge:['☑','teal']};
const prefixes=[[/^(fundstelle|quelle)/,'📚','blue'],[/^(achtung|warnung)/,'⚠','gold'],[/^(merksatz|praxis-merksatz|merke)/,'💡','gold'],[/^hinweis/,'ℹ','teal'],[/^(definition|legaldefinition)/,'📖','teal'],[/^checkliste/,'☑','teal'],[/^(lernziel|ihre lernziele)/,'🎯','teal'],[/^(problem|rechtsfrage)/,'?','indigo']];
export function headingStyle(title=''){
 const role=title.match(/^Rollen? (\d{1,2})$/);if(role)return {symbol:role[1],tone:'blue',title:'Rolle',step:true};
 const steps=['Tod feststellen','Prognose klären','Willen ermitteln','Rollen trennen','Prozess sichern'];const step=steps.indexOf(title),numbered=title.match(/^(\d{1,2}[.)]?|[A-C][.)])\s+(.+)$/);
 if(step>=0)return {symbol:String(step+1),tone:'teal',title,step:true};if(numbered)return {symbol:numbered[1].replace(/[.)]/g,''),tone:'teal',title:numbered[2],step:true};
 const key=title.toLocaleLowerCase('de').trim(),entry=exact[key],prefix=prefixes.find(([re])=>re.test(key));return {symbol:entry?.[0]??prefix?.[1]??'',tone:entry?.[1]??prefix?.[2]??'plain',title,step:false};
}
export function protectReferences(text){return text.replace(/(§{1,2}|\bArt\.|\bAbs\.|\bSatz|\bNr\.)[ \t]+(?=\d)/g,'$1\u00a0');}
const supplementaryHeadings={"454-body-0": "Vom Tatbestand zur Rechtsfolge", "454-body-1": "Normen präzise zitieren", "455-body-0": "Auslegungsmethoden und Ethik", "455-body-1": "Grenzen im Strafrecht", "456-body-0": "Definitionen im Vergleich", "456-body-1": "Einwilligungsfähigkeit gesondert prüfen", "457-body-0": "Rechtliche Einordnung", "457-body-1": "Prüfung im konkreten Einsatz", "458-body-0": "Dokumentation im Einsatz", "458-body-1": "Übergabe und erkennbare Nachträge", "459-body-0": "Allgemeine Hilfeleistungspflicht", "459-body-1": "Besondere Garantenstellung", "460-body-0": "Vorsatz und Fahrlässigkeit unterscheiden", "460-body-1": "Wann beginnt ein strafbarer Versuch?", "461-body-0": "Schweigepflicht gegenüber Dritten", "461-body-1": "Übergabe und akute Gefahren", "462-body-0": "Arbeitsvertrag und weitere Regelungen", "462-body-1": "Voraussetzungen einer Befristung", "463-body-0": "Teilzeit und Brückenteilzeit", "463-body-1": "Berufsspezifische Ausbildungsregeln", "464-body-0": "Form und Kündigungsschutz", "464-body-1": "Fristen und Einzelfallprüfung", "465-body-0": "Die rechtsfähige Praxis-GbR", "465-body-1": "Vertretung und persönliche Haftung", "466-body-0": "Selbstbestimmte Ablehnung", "466-body-1": "Prüfung und Dokumentation", "467-body-0": "Patientenverfügung und Vertretung", "467-body-1": "Grenzen unaufschiebbarer Behandlung", "468-body-0": "Voraussetzungen des § 2a NotSanG", "468-body-1": "Grenzen der eigenen Befugnis", "469-body-0": "Qualifikation und Einweisung", "469-body-1": "Sicherer Einsatz und Verantwortlichkeiten", "470-body-0": "Aufgaben und Zuständigkeiten", "470-body-1": "Finanzierung und Fahrkosten", "471-body-0": "Public Health und öffentlicher Gesundheitsdienst", "471-body-1": "Institutionen richtig zuordnen", "472-body-0": "GKV: Leistungen und Beiträge", "472-body-1": "PKV: Tarif und Lebensplanung", "473-body-0": "Kassen, KV und weitere Akteure", "473-body-1": "Vergütung und Krankenhausfinanzierung", "474-body-0": "Wirtschaftlichkeit und G-BA", "474-body-1": "Leitlinien, Richtlinien und neue Methoden"};
export function slideSections(blocks){const sections=[],sources=[];for(const b of blocks){if(supplementaryHeadings[b.id]&&!b.continuesPrevious)sections.push({title:supplementaryHeadings[b.id],blocks:[]});if(b.role==='source'){if(b.text&&!sources.includes(b.text))sources.push(b.text);continue;}if(b.role==='heading'){const title=b.text.replace(/ · Fortsetzung$/,'');if(sections.at(-1)?.title!==title)sections.push({title,blocks:[]});}else{if(!sections.length||b.image)sections.push({title:'',blocks:[]});const section=sections.at(-1),last=section.blocks.at(-1);if(b.continuesPrevious&&last?.role==='body'&&b.role==='body')section.blocks[section.blocks.length-1]={...last,text:last.text+' '+b.text,links:[...(last.links??[]),...(b.links??[])]};else section.blocks.push(b);}}return {sections,sources};}

export const emphasisTerms=['Einwilligungsfähigkeit','Patientenwille','Beweislast','Aufklärungspflicht','Verhältnismäßigkeit','Garantenstellung','Dokumentationspflicht','Patientenverfügung','Behandlungsfehler','Selbstbestimmungsrecht','Schweigepflicht','Amtshaftung','Wirtschaftlichkeitsgebot','Facharztstandard','Beweislastumkehr','rechtfertigende Indikation','mutmaßlicher Wille','Recht auf Nichtwissen','Anfangsverdacht','Unschuldsvermutung','Sachleistungsprinzip','Kostenerstattungsprinzip','Versicherungspflichtgrenze','Gemeinsamer Bundesausschuss','Solidaritätsprinzip','Subsidiaritätsprinzip'];
export function emphasisRanges(text){const found=[];for(const term of emphasisTerms){if(found.length===2)break;const match=new RegExp('(?<![\\p{L}])'+term+'(?![\\p{L}])','u').exec(text);if(match)found.push({start:match.index,end:match.index+term.length});}return found.sort((a,b)=>a.start-b.start);}
export function readingParts(text){
 const value=protectReferences(text).trim();if(value.startsWith('•'))return {kind:'bullets',items:value.split('•').map(x=>x.trim()).filter(Boolean)};
 const matches=[...value.matchAll(/(?:^|\s)(\d+)\.\s+/g)],numbers=matches.map(m=>Number(m[1]));
 if(matches.length>1&&matches[0].index===0&&numbers[0]>0&&numbers.every((n,i)=>n===numbers[0]+i))return {kind:'steps',start:numbers[0],items:matches.map((m,i)=>value.slice(m.index+m[0].length,matches[i+1]?.index??value.length).trim())};
 let paragraphs=value.replace(/(?<=[.!?;]) (Heutiger Lehrtransfer|Weitere Begründung|Tragende Aussage|Praxis|Rechtsstand|Begründung|Genehmigung|Lehrtransfer|Historische Einordnung): /g,'\n\n$1: ');
 const statutory=[...paragraphs.matchAll(/(?:^|\s)\((\d+)\)\s+/g)];if(statutory.length>1&&statutory[0].index===0&&statutory.every((m,i)=>Number(m[1])===Number(statutory[0][1])+i))paragraphs=paragraphs.replace(/\s+(?=\(\d+\)\s)/g,'\n\n');
 return {kind:'paragraphs',items:paragraphs.split('\n\n').filter(Boolean)};
}
export function layoutForSlide(slide){
 const sections=slideSections(slide.blocks??[]).sections;
 if(Number(slide.id)===1)return 'cover';
 const short=sections.filter(s=>s.title&&s.blocks.every(b=>!b.image)&&s.blocks.reduce((n,b)=>n+(b.text?.length??0),0)<600);
 if(sections.length>=4&&sections.length<=8&&short.length===sections.length&&sections.filter(s=>/^Rollen? \d/.test(s.title)).length>=4)return 'roles';
 if(sections.length>=2&&sections.length<=6&&short.length===sections.length)return 'comparison';
 if(sections.length===1&&/Zitat|Kernaussage|Tragende Aussage/i.test(sections[0].title??''))return 'statement';
 return 'reading';
}
