import {searchIndex,searchEntries} from './search-engine.mjs?v=20260930ao';
import {safeURL} from './policy.mjs?v=20260930ao';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
const resultKinds={Kurse:['📚','teal'],Folien:['▤','blue'],Begriffe:['📖','teal'],Berufsstart:['🩺','gold'],Gesundheitsberufe:['✚','blue'],Schaubilder:['◈','gold'],Urteile:['⚖','indigo'],Normen:['§','indigo'],Podcast:['🎙','gold']};
function excerpt(text,query){const plain=text.replace(/\s+/g,' ').trim(),term=query.trim().split(/\s+/)[0],index=plain.toLocaleLowerCase('de').indexOf(term.toLocaleLowerCase('de'));let start=Math.max(0,index-65);if(start){const nextSpace=plain.indexOf(' ',start);if(nextSpace>=0&&nextSpace<start+25)start=nextSpace+1;}let end=Math.min(plain.length,start+240);if(end<plain.length){const lastSpace=plain.lastIndexOf(' ',end);if(lastSpace>end-25)end=lastSpace;}return (start?'… ':'')+plain.slice(start,end)+(end<plain.length?' …':'');}
function highlighted(text,query){const span=el('span'),terms=query.trim().split(/\s+/).filter(Boolean).map(t=>t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));if(!terms.length){span.textContent=text;return span;}const re=new RegExp('('+terms.join('|')+')','ig');for(const [i,part] of text.split(re).entries())span.append(el(i%2?'mark':'span',part));return span;}
export async function renderSearch(main,catalog,auth,isCurrent){
  const hero=el('section',null,'knowledge-banner');hero.append(el('p','FINDEN · VERSTEHEN · WEITERLERNEN','section-number'),el('h1','🔎 Die Lernplattform durchsuchen'),el('p','Kurse, Folien, Begriffe, Urteile, Normen und Podcastfolgen an einem Ort.'));main.append(hero);
  const input=el('input');input.type='search';input.placeholder='Begriff, Kursnummer, Paragraph oder Thema';input.setAttribute('aria-label','Gesamte Lernplattform durchsuchen');const filter=el('select');filter.setAttribute('aria-label','Suchbereich');for(const type of ['Alle Bereiche','Kurse','Folien','Begriffe','Berufsstart','Gesundheitsberufe','Schaubilder','Urteile','Normen','Podcast']){const o=el('option',type);o.value=type;filter.append(o);}const controls=el('div',null,'search-controls');controls.append(input,filter);const status=el('p','Suchverzeichnis wird geladen …','subtle');status.role='status';const results=el('div',null,'search-results');main.append(controls,status,results);
  const [library,episodes]=await Promise.all([fetch('./library.json?v=20260930ao').then(r=>{if(!r.ok)throw Error();return r.json();}),fetch('./podcast-episodes.json?v=20260930ao').then(r=>{if(!r.ok)throw Error();return r.json();})]);if(!isCurrent())return;
  let entries=searchIndex(catalog,library,episodes),limit=24;
  function render(){results.replaceChildren();if(!input.value.trim()){status.textContent='Suchen Sie beispielsweise nach Einwilligung, PJ, § 630h oder Kurs 03.';return;}const found=searchEntries(entries,input.value).filter(e=>filter.value==='Alle Bereiche'||e.type===filter.value);status.textContent=`${found.length} Treffer · geschützte Volltexte nur mit aktivem Zugang`;for(const e of found.slice(0,limit)){const [symbol,tone]=resultKinds[e.type]??['⌕','teal'],card=el('article',null,`card search-result search-tone-${tone}`),title=el('h2'),a=el('a');a.href=e.external?safeURL(e.href)||'#norms':e.href;if(e.external){a.target='_blank';a.rel='noopener noreferrer';}a.append(highlighted(e.title,input.value));title.append(a);const label=el('p',null,'search-result-kind');label.append(el('span',symbol,'search-result-symbol'),el('span',e.type));if(e.preview)label.append(el('span','Vorschau','search-preview'));card.append(label,title);const p=el('p');p.append(highlighted(excerpt(e.text,input.value),input.value));const action=el('a',e.external?'Quelle öffnen ↗':'Inhalt öffnen →','search-result-action');action.href=a.href;if(e.external){action.target='_blank';action.rel='noopener noreferrer';}card.append(p,action);results.append(card);}if(found.length>limit){const more=el('button','Weitere Treffer anzeigen');more.type='button';more.onclick=()=>{limit+=24;render();};results.append(more);}if(!found.length)results.append(el('p','Kein passender Treffer. Versuchen Sie einen allgemeineren Begriff.','notice'));}
  input.oninput=()=>{limit=24;render();};filter.onchange=()=>{limit=24;render();};render();
  if(auth?.getSearchContent)try{const authorized=await auth.getSearchContent();if(!isCurrent())return;entries=searchIndex(catalog,library,episodes,authorized);render();}catch{if(isCurrent())main.append(el('p','Zusätzliche freigeschaltete Volltexte konnten gerade nicht geladen werden. Die Suche in kostenlosen Inhalten und Vorschauen bleibt verfügbar.','notice'));}
}
